/**
 * Clothing Taxonomy - Comprehensive Uzbek Taxonomy
 * 
 * Audience → Segment → Leaf structure
 * 250+ leaf items for marketplace coverage
 */

export type Audience = 'erkaklar' | 'ayollar' | 'bolalar' | 'unisex'
export type Segment = 'kiyim' | 'oyoq_kiyim' | 'aksessuar' | 'ichki_kiyim' | 'sport' | 'milliy'

export interface TaxonNode {
  id: string // Stable ID: "ayollar.oyoq_kiyim.krossovka"
  labelUz: string // Uzbek label
  synonymsUz?: string[] // Search help
  audience: Audience
  segment: Segment
  pathUz: string // "Ayollar > Oyoq kiyim > Krossovka"
  leaf: boolean
  descriptionUz?: string // Optional description
  // Field profiling for AI questioning
  requiredFieldsOverride?: string[] // Override required fields for this specific leaf
  suggestedFields?: string[] // Additional fields to suggest for this leaf
}

export const CLOTHING_TAXONOMY: TaxonNode[] = [
  // ============================================
  // AYOLLAR - KIYIM
  // ============================================
  {
    id: 'ayollar.kiyim.futbolka',
    labelUz: 'Futbolka',
    synonymsUz: ['t-shirt', 'ti-short', 'futbolka'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Futbolka',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.koylak',
    labelUz: 'Ko\'ylak',
    synonymsUz: ['bluzka', 'ko\'ylak', 'shirt'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Ko\'ylak',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.bluzka',
    labelUz: 'Bluzka',
    synonymsUz: ['blouse', 'bluzka', 'ko\'ylak'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Bluzka',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.shim',
    labelUz: 'Shim',
    synonymsUz: ['pants', 'shim', 'shalvar'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Shim',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.jinsi',
    labelUz: 'Jinsi',
    synonymsUz: ['jeans', 'jinsi', 'jinsiy'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Jinsi',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.yubka',
    labelUz: 'Yubka',
    synonymsUz: ['skirt', 'yubka'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Yubka',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.platye',
    labelUz: 'Platye',
    synonymsUz: ['dress', 'platye', 'ko\'ylak'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Platye',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.pidjak',
    labelUz: 'Pidjak',
    synonymsUz: ['jacket', 'pidjak', 'kurtka'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Pidjak',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.palto',
    labelUz: 'Palto',
    synonymsUz: ['coat', 'palto', 'kurtka'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Palto',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.kurtka',
    labelUz: 'Kurtka',
    synonymsUz: ['jacket', 'kurtka', 'pidjak'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Kurtka',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.sviter',
    labelUz: 'Sviter',
    synonymsUz: ['sweater', 'sviter', 'jumper'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Sviter',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.xudi',
    labelUz: 'Xudi',
    synonymsUz: ['hoodie', 'xudi', 'kapshon'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Xudi',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.kombinezon',
    labelUz: 'Kombinezon',
    synonymsUz: ['overall', 'kombinezon', 'jumpsuit'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Kombinezon',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.shorts',
    labelUz: 'Shorts',
    synonymsUz: ['shorts', 'qisqa shim'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Shorts',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.kostyum',
    labelUz: 'Kostyum',
    synonymsUz: ['suit', 'kostyum', 'komplekt'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Kostyum',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.sarafan',
    labelUz: 'Sarafan',
    synonymsUz: ['sarafan', 'pinafore'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Sarafan',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.tunika',
    labelUz: 'Tunika',
    synonymsUz: ['tunic', 'tunika'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Tunika',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.kardigan',
    labelUz: 'Kardigan',
    synonymsUz: ['cardigan', 'kardigan'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Kardigan',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.zhile',
    labelUz: 'Zhile',
    synonymsUz: ['vest', 'zhile', 'bezrukavka'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Zhile',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.kofta',
    labelUz: 'Ko\'fta',
    synonymsUz: ['kofta', 'long sleeve'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Ko\'fta',
    leaf: true,
  },

  // ============================================
  // AYOLLAR - OYOQ KIYIM
  // ============================================
  {
    id: 'ayollar.oyoq_kiyim.krossovka_sport',
    labelUz: 'Krossovka (Sport)',
    synonymsUz: ['sport krossovka', 'training shoes', 'athletic'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Krossovka (Sport)',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.krossovka_kucha',
    labelUz: 'Krossovka (Ko\'cha)',
    synonymsUz: ['casual sneakers', 'street sneakers', 'ko\'cha krossovka'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Krossovka (Ko\'cha)',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.krossovka_yugurish',
    labelUz: 'Krossovka (Yugurish)',
    synonymsUz: ['running shoes', 'yugurish krossovka', 'jogging'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Krossovka (Yugurish)',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.krossovka_trail',
    labelUz: 'Krossovka (Trail)',
    synonymsUz: ['trail running', 'hiking shoes', 'trail'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Krossovka (Trail)',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.krossovka_basketbol',
    labelUz: 'Krossovka (Basketbol)',
    synonymsUz: ['basketball shoes', 'basketbol krossovka'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Krossovka (Basketbol)',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.krossovka_futbol',
    labelUz: 'Krossovka (Futbol)',
    synonymsUz: ['football boots', 'futbol krossovka', 'cleats'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Krossovka (Futbol)',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.krossovka_futzal',
    labelUz: 'Krossovka (Futzal)',
    synonymsUz: ['futsal shoes', 'futzal krossovka', 'indoor'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Krossovka (Futzal)',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.tufli',
    labelUz: 'Tufli',
    synonymsUz: ['shoes', 'tufli', 'baletka'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Tufli',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.etik',
    labelUz: 'Etik',
    synonymsUz: ['boots', 'etik', 'butsi'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Etik',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.botinka',
    labelUz: 'Botinka',
    synonymsUz: ['ankle boots', 'botinka', 'short boots'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Botinka',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.sandali',
    labelUz: 'Sandali',
    synonymsUz: ['sandals', 'sandali', 'sandal'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Sandali',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.shippak',
    labelUz: 'Shippak',
    synonymsUz: ['slippers', 'shippak', 'domashnyaya obuv'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Shippak',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.mokasin',
    labelUz: 'Mokasin',
    synonymsUz: ['moccasins', 'mokasin', 'loafers'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Mokasin',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.lofer',
    labelUz: 'Lofer',
    synonymsUz: ['loafers', 'lofer', 'mokasin'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Lofer',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.baletka',
    labelUz: 'Baletka',
    synonymsUz: ['ballet flats', 'baletka', 'flat shoes'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Baletka',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.tufli_poshnali',
    labelUz: 'Tufli (Poshnali)',
    synonymsUz: ['heels', 'poshnali tufli', 'high heels'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Tufli (Poshnali)',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.butsi',
    labelUz: 'Butsi',
    synonymsUz: ['boots', 'butsi', 'etik'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Butsi',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.slanets',
    labelUz: 'Slanets',
    synonymsUz: ['flip flops', 'slanets', 'shlyapa'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Slanets',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.uggi',
    labelUz: 'Uggi',
    synonymsUz: ['ugg boots', 'uggi', 'warm boots'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Uggi',
    leaf: true,
  },

  // ============================================
  // AYOLLAR - AKSSESUAR
  // ============================================
  {
    id: 'ayollar.aksessuar.sumka',
    labelUz: 'Sumka',
    synonymsUz: ['bag', 'sumka', 'ryukzak'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Sumka',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.ryukzak',
    labelUz: 'Ryukzak',
    synonymsUz: ['backpack', 'ryukzak', 'sumka'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Ryukzak',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.kamar',
    labelUz: 'Kamar',
    synonymsUz: ['belt', 'kamar', 'remen'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Kamar',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.soat',
    labelUz: 'Soat',
    synonymsUz: ['watch', 'soat', 'clock'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Soat',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.kozoynak',
    labelUz: 'Ko\'zoynak',
    synonymsUz: ['glasses', 'ko\'zoynak', 'ochki'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Ko\'zoynak',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.sharf',
    labelUz: 'Sharf',
    synonymsUz: ['scarf', 'sharf', 'platok'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Sharf',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.shlyapa',
    labelUz: 'Shlyapa',
    synonymsUz: ['hat', 'shlyapa', 'kepka'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Shlyapa',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.kepka',
    labelUz: 'Kepka',
    synonymsUz: ['cap', 'kepka', 'baseball cap'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Kepka',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.qolqop',
    labelUz: 'Qo\'lqop',
    synonymsUz: ['gloves', 'qo\'lqop', 'perchatki'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Qo\'lqop',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.sirga',
    labelUz: 'Sirga',
    synonymsUz: ['earrings', 'sirga', 'ser\'gi'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Sirga',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.uzuk',
    labelUz: 'Uzuk',
    synonymsUz: ['ring', 'uzuk', 'kol\'tso'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Uzuk',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.hamyon',
    labelUz: 'Hamyon',
    synonymsUz: ['wallet', 'hamyon', 'koshelek'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Hamyon',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.kluchnitsa',
    labelUz: 'Kalit quti',
    synonymsUz: ['keychain', 'kluchnitsa', 'key holder'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Kalit quti',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.brosh',
    labelUz: 'Brosh',
    synonymsUz: ['brooch', 'brosh', 'znachok'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Brosh',
    leaf: true,
  },

  // ============================================
  // AYOLLAR - ICHKI KIYIM
  // ============================================
  {
    id: 'ayollar.ichki_kiyim.paypoq',
    labelUz: 'Paypoq',
    synonymsUz: ['socks', 'paypoq', 'noski'],
    audience: 'ayollar',
    segment: 'ichki_kiyim',
    pathUz: 'Ayollar > Ichki kiyim > Paypoq',
    leaf: true,
  },
  {
    id: 'ayollar.ichki_kiyim.sutyen',
    labelUz: 'Sutyen',
    synonymsUz: ['bra', 'sutyen', 'bustgalter'],
    audience: 'ayollar',
    segment: 'ichki_kiyim',
    pathUz: 'Ayollar > Ichki kiyim > Sutyen',
    leaf: true,
  },
  {
    id: 'ayollar.ichki_kiyim.mayka',
    labelUz: 'Mayka',
    synonymsUz: ['undershirt', 'mayka', 'majka'],
    audience: 'ayollar',
    segment: 'ichki_kiyim',
    pathUz: 'Ayollar > Ichki kiyim > Mayka',
    leaf: true,
  },
  {
    id: 'ayollar.ichki_kiyim.pijama',
    labelUz: 'Pijama',
    synonymsUz: ['pajamas', 'pijama', 'nightwear'],
    audience: 'ayollar',
    segment: 'ichki_kiyim',
    pathUz: 'Ayollar > Ichki kiyim > Pijama',
    leaf: true,
  },
  {
    id: 'ayollar.ichki_kiyim.termokiyim',
    labelUz: 'Termokiyim',
    synonymsUz: ['thermal', 'termokiyim', 'termobele'],
    audience: 'ayollar',
    segment: 'ichki_kiyim',
    pathUz: 'Ayollar > Ichki kiyim > Termokiyim',
    leaf: true,
  },
  {
    id: 'ayollar.ichki_kiyim.ichki_kiyim',
    labelUz: 'Ichki kiyim',
    synonymsUz: ['underwear', 'ichki kiyim', 'bele'],
    audience: 'ayollar',
    segment: 'ichki_kiyim',
    pathUz: 'Ayollar > Ichki kiyim > Ichki kiyim',
    leaf: true,
  },

  // ============================================
  // AYOLLAR - SPORT
  // ============================================
  {
    id: 'ayollar.sport.sport_kostyum',
    labelUz: 'Sport kostyum',
    synonymsUz: ['sport suit', 'sport kostyum', 'tracksuit'],
    audience: 'ayollar',
    segment: 'sport',
    pathUz: 'Ayollar > Sport > Sport kostyum',
    leaf: true,
  },
  {
    id: 'ayollar.sport.tayt',
    labelUz: 'Tayt',
    synonymsUz: ['leggings', 'tayt', 'legins'],
    audience: 'ayollar',
    segment: 'sport',
    pathUz: 'Ayollar > Sport > Tayt',
    leaf: true,
  },
  {
    id: 'ayollar.sport.sport_futbolka',
    labelUz: 'Sport futbolka',
    synonymsUz: ['sport t-shirt', 'sport futbolka', 'athletic shirt'],
    audience: 'ayollar',
    segment: 'sport',
    pathUz: 'Ayollar > Sport > Sport futbolka',
    leaf: true,
  },
  {
    id: 'ayollar.sport.trening_oyoq_kiyim',
    labelUz: 'Trening oyoq kiyim',
    synonymsUz: ['training shoes', 'trening', 'workout shoes'],
    audience: 'ayollar',
    segment: 'sport',
    pathUz: 'Ayollar > Sport > Trening oyoq kiyim',
    leaf: true,
  },
  {
    id: 'ayollar.sport.fitness',
    labelUz: 'Fitness kiyim',
    synonymsUz: ['fitness wear', 'fitness', 'gym clothes'],
    audience: 'ayollar',
    segment: 'sport',
    pathUz: 'Ayollar > Sport > Fitness kiyim',
    leaf: true,
  },
  {
    id: 'ayollar.sport.yugurish_kiyimi',
    labelUz: 'Yugurish kiyimi',
    synonymsUz: ['running gear', 'yugurish', 'running clothes'],
    audience: 'ayollar',
    segment: 'sport',
    pathUz: 'Ayollar > Sport > Yugurish kiyimi',
    leaf: true,
  },

  // ============================================
  // AYOLLAR - MILLIY
  // ============================================
  {
    id: 'ayollar.milliy.chopon',
    labelUz: 'Chopon',
    synonymsUz: ['chopon', 'traditional coat', 'milliy chopon'],
    audience: 'ayollar',
    segment: 'milliy',
    pathUz: 'Ayollar > Milliy > Chopon',
    leaf: true,
  },
  {
    id: 'ayollar.milliy.doppi',
    labelUz: 'Do\'ppi',
    synonymsUz: ['do\'ppi', 'skullcap', 'milliy shlyapa'],
    audience: 'ayollar',
    segment: 'milliy',
    pathUz: 'Ayollar > Milliy > Do\'ppi',
    leaf: true,
  },
  {
    id: 'ayollar.milliy.atlas_koylak',
    labelUz: 'Atlas/Adras ko\'ylak',
    synonymsUz: ['atlas', 'adras', 'silk dress', 'milliy ko\'ylak'],
    audience: 'ayollar',
    segment: 'milliy',
    pathUz: 'Ayollar > Milliy > Atlas/Adras ko\'ylak',
    leaf: true,
  },
  {
    id: 'ayollar.milliy.milliy_libos',
    labelUz: 'Milliy libos',
    synonymsUz: ['traditional dress', 'milliy libos', 'national costume'],
    audience: 'ayollar',
    segment: 'milliy',
    pathUz: 'Ayollar > Milliy > Milliy libos',
    leaf: true,
  },
  {
    id: 'ayollar.milliy.belbog',
    labelUz: 'Belbog\'',
    synonymsUz: ['belt', 'belbog', 'milliy kamar'],
    audience: 'ayollar',
    segment: 'milliy',
    pathUz: 'Ayollar > Milliy > Belbog\'',
    leaf: true,
  },
  {
    id: 'ayollar.milliy.mahsi',
    labelUz: 'Mahsi/Kalish',
    synonymsUz: ['mahsi', 'kalish', 'traditional boots', 'milliy etik'],
    audience: 'ayollar',
    segment: 'milliy',
    pathUz: 'Ayollar > Milliy > Mahsi/Kalish',
    leaf: true,
  },

  // ============================================
  // ERKAKLAR - KIYIM
  // ============================================
  {
    id: 'erkaklar.kiyim.futbolka',
    labelUz: 'Futbolka',
    synonymsUz: ['t-shirt', 'ti-short', 'futbolka'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Futbolka',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.koylak',
    labelUz: 'Ko\'ylak',
    synonymsUz: ['shirt', 'ko\'ylak', 'rubashka'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Ko\'ylak',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.shim',
    labelUz: 'Shim',
    synonymsUz: ['pants', 'shim', 'bryuki'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Shim',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.jinsi',
    labelUz: 'Jinsi',
    synonymsUz: ['jeans', 'jinsi', 'dzhinsy'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Jinsi',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.pidjak',
    labelUz: 'Pidjak',
    synonymsUz: ['jacket', 'pidjak', 'kurtka'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Pidjak',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.palto',
    labelUz: 'Palto',
    synonymsUz: ['coat', 'palto', 'kurtka'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Palto',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.kurtka',
    labelUz: 'Kurtka',
    synonymsUz: ['jacket', 'kurtka', 'pidjak'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Kurtka',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.sviter',
    labelUz: 'Sviter',
    synonymsUz: ['sweater', 'sviter', 'jumper'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Sviter',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.xudi',
    labelUz: 'Xudi',
    synonymsUz: ['hoodie', 'xudi', 'kapshon'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Xudi',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.shorts',
    labelUz: 'Shorts',
    synonymsUz: ['shorts', 'qisqa shim'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Shorts',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.kostyum',
    labelUz: 'Kostyum',
    synonymsUz: ['suit', 'kostyum', 'komplekt'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Kostyum',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.kofta',
    labelUz: 'Ko\'fta',
    synonymsUz: ['long sleeve', 'kofta', 'rubashka'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Ko\'fta',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.zhile',
    labelUz: 'Zhile',
    synonymsUz: ['vest', 'zhile', 'bezrukavka'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Zhile',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.kardigan',
    labelUz: 'Kardigan',
    synonymsUz: ['cardigan', 'kardigan'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Kardigan',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.polo',
    labelUz: 'Polo',
    synonymsUz: ['polo shirt', 'polo', 'rubashka'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Polo',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.mayka',
    labelUz: 'Mayka',
    synonymsUz: ['tank top', 'mayka', 'majka'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Mayka',
    leaf: true,
  },

  // ============================================
  // ERKAKLAR - OYOQ KIYIM
  // ============================================
  {
    id: 'erkaklar.oyoq_kiyim.krossovka_sport',
    labelUz: 'Krossovka (Sport)',
    synonymsUz: ['sport krossovka', 'training shoes', 'athletic'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Krossovka (Sport)',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.krossovka_kucha',
    labelUz: 'Krossovka (Ko\'cha)',
    synonymsUz: ['casual sneakers', 'street sneakers', 'ko\'cha krossovka'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Krossovka (Ko\'cha)',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.krossovka_yugurish',
    labelUz: 'Krossovka (Yugurish)',
    synonymsUz: ['running shoes', 'yugurish krossovka', 'jogging'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Krossovka (Yugurish)',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.krossovka_trail',
    labelUz: 'Krossovka (Trail)',
    synonymsUz: ['trail running', 'hiking shoes', 'trail'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Krossovka (Trail)',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.krossovka_basketbol',
    labelUz: 'Krossovka (Basketbol)',
    synonymsUz: ['basketball shoes', 'basketbol krossovka'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Krossovka (Basketbol)',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.krossovka_futbol',
    labelUz: 'Krossovka (Futbol)',
    synonymsUz: ['football boots', 'futbol krossovka', 'cleats'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Krossovka (Futbol)',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.krossovka_futzal',
    labelUz: 'Krossovka (Futzal)',
    synonymsUz: ['futsal shoes', 'futzal krossovka', 'indoor'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Krossovka (Futzal)',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.tufli',
    labelUz: 'Tufli',
    synonymsUz: ['shoes', 'tufli', 'formal shoes'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Tufli',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.etik',
    labelUz: 'Etik',
    synonymsUz: ['boots', 'etik', 'butsi'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Etik',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.botinka',
    labelUz: 'Botinka',
    synonymsUz: ['ankle boots', 'botinka', 'short boots'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Botinka',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.sandali',
    labelUz: 'Sandali',
    synonymsUz: ['sandals', 'sandali', 'sandal'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Sandali',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.shippak',
    labelUz: 'Shippak',
    synonymsUz: ['slippers', 'shippak', 'domashnyaya obuv'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Shippak',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.mokasin',
    labelUz: 'Mokasin',
    synonymsUz: ['moccasins', 'mokasin', 'loafers'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Mokasin',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.lofer',
    labelUz: 'Lofer',
    synonymsUz: ['loafers', 'lofer', 'mokasin'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Lofer',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.butsi',
    labelUz: 'Butsi',
    synonymsUz: ['boots', 'butsi', 'etik'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Butsi',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.uggi',
    labelUz: 'Uggi',
    synonymsUz: ['ugg boots', 'uggi', 'warm boots'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Uggi',
    leaf: true,
  },

  // ============================================
  // ERKAKLAR - AKSSESUAR
  // ============================================
  {
    id: 'erkaklar.aksessuar.sumka',
    labelUz: 'Sumka',
    synonymsUz: ['bag', 'sumka', 'ryukzak'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Sumka',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.ryukzak',
    labelUz: 'Ryukzak',
    synonymsUz: ['backpack', 'ryukzak', 'sumka'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Ryukzak',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.kamar',
    labelUz: 'Kamar',
    synonymsUz: ['belt', 'kamar', 'remen'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Kamar',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.soat',
    labelUz: 'Soat',
    synonymsUz: ['watch', 'soat', 'clock'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Soat',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.kozoynak',
    labelUz: 'Ko\'zoynak',
    synonymsUz: ['glasses', 'ko\'zoynak', 'ochki'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Ko\'zoynak',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.sharf',
    labelUz: 'Sharf',
    synonymsUz: ['scarf', 'sharf', 'platok'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Sharf',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.shlyapa',
    labelUz: 'Shlyapa',
    synonymsUz: ['hat', 'shlyapa', 'kepka'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Shlyapa',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.kepka',
    labelUz: 'Kepka',
    synonymsUz: ['cap', 'kepka', 'baseball cap'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Kepka',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.qolqop',
    labelUz: 'Qo\'lqop',
    synonymsUz: ['gloves', 'qo\'lqop', 'perchatki'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Qo\'lqop',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.hamyon',
    labelUz: 'Hamyon',
    synonymsUz: ['wallet', 'hamyon', 'koshelek'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Hamyon',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.kluchnitsa',
    labelUz: 'Kalit quti',
    synonymsUz: ['keychain', 'kluchnitsa', 'key holder'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Kalit quti',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.galstuk',
    labelUz: 'Galstuk',
    synonymsUz: ['tie', 'galstuk', 'necktie'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Galstuk',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.remen',
    labelUz: 'Remen',
    synonymsUz: ['belt', 'remen', 'kamar'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Remen',
    leaf: true,
  },

  // ============================================
  // ERKAKLAR - ICHKI KIYIM
  // ============================================
  {
    id: 'erkaklar.ichki_kiyim.paypoq',
    labelUz: 'Paypoq',
    synonymsUz: ['socks', 'paypoq', 'noski'],
    audience: 'erkaklar',
    segment: 'ichki_kiyim',
    pathUz: 'Erkaklar > Ichki kiyim > Paypoq',
    leaf: true,
  },
  {
    id: 'erkaklar.ichki_kiyim.mayka',
    labelUz: 'Mayka',
    synonymsUz: ['undershirt', 'mayka', 'majka'],
    audience: 'erkaklar',
    segment: 'ichki_kiyim',
    pathUz: 'Erkaklar > Ichki kiyim > Mayka',
    leaf: true,
  },
  {
    id: 'erkaklar.ichki_kiyim.pijama',
    labelUz: 'Pijama',
    synonymsUz: ['pajamas', 'pijama', 'nightwear'],
    audience: 'erkaklar',
    segment: 'ichki_kiyim',
    pathUz: 'Erkaklar > Ichki kiyim > Pijama',
    leaf: true,
  },
  {
    id: 'erkaklar.ichki_kiyim.termokiyim',
    labelUz: 'Termokiyim',
    synonymsUz: ['thermal', 'termokiyim', 'termobele'],
    audience: 'erkaklar',
    segment: 'ichki_kiyim',
    pathUz: 'Erkaklar > Ichki kiyim > Termokiyim',
    leaf: true,
  },
  {
    id: 'erkaklar.ichki_kiyim.ichki_kiyim',
    labelUz: 'Ichki kiyim',
    synonymsUz: ['underwear', 'ichki kiyim', 'bele'],
    audience: 'erkaklar',
    segment: 'ichki_kiyim',
    pathUz: 'Erkaklar > Ichki kiyim > Ichki kiyim',
    leaf: true,
  },

  // ============================================
  // ERKAKLAR - SPORT
  // ============================================
  {
    id: 'erkaklar.sport.sport_kostyum',
    labelUz: 'Sport kostyum',
    synonymsUz: ['sport suit', 'sport kostyum', 'tracksuit'],
    audience: 'erkaklar',
    segment: 'sport',
    pathUz: 'Erkaklar > Sport > Sport kostyum',
    leaf: true,
  },
  {
    id: 'erkaklar.sport.sport_futbolka',
    labelUz: 'Sport futbolka',
    synonymsUz: ['sport t-shirt', 'sport futbolka', 'athletic shirt'],
    audience: 'erkaklar',
    segment: 'sport',
    pathUz: 'Erkaklar > Sport > Sport futbolka',
    leaf: true,
  },
  {
    id: 'erkaklar.sport.trening_oyoq_kiyim',
    labelUz: 'Trening oyoq kiyim',
    synonymsUz: ['training shoes', 'trening', 'workout shoes'],
    audience: 'erkaklar',
    segment: 'sport',
    pathUz: 'Erkaklar > Sport > Trening oyoq kiyim',
    leaf: true,
  },
  {
    id: 'erkaklar.sport.fitness',
    labelUz: 'Fitness kiyim',
    synonymsUz: ['fitness wear', 'fitness', 'gym clothes'],
    audience: 'erkaklar',
    segment: 'sport',
    pathUz: 'Erkaklar > Sport > Fitness kiyim',
    leaf: true,
  },
  {
    id: 'erkaklar.sport.yugurish_kiyimi',
    labelUz: 'Yugurish kiyimi',
    synonymsUz: ['running gear', 'yugurish', 'running clothes'],
    audience: 'erkaklar',
    segment: 'sport',
    pathUz: 'Erkaklar > Sport > Yugurish kiyimi',
    leaf: true,
  },

  // ============================================
  // ERKAKLAR - MILLIY
  // ============================================
  {
    id: 'erkaklar.milliy.chopon',
    labelUz: 'Chopon',
    synonymsUz: ['chopon', 'traditional coat', 'milliy chopon'],
    audience: 'erkaklar',
    segment: 'milliy',
    pathUz: 'Erkaklar > Milliy > Chopon',
    leaf: true,
  },
  {
    id: 'erkaklar.milliy.doppi',
    labelUz: 'Do\'ppi',
    synonymsUz: ['do\'ppi', 'skullcap', 'milliy shlyapa'],
    audience: 'erkaklar',
    segment: 'milliy',
    pathUz: 'Erkaklar > Milliy > Do\'ppi',
    leaf: true,
  },
  {
    id: 'erkaklar.milliy.milliy_libos',
    labelUz: 'Milliy libos',
    synonymsUz: ['traditional dress', 'milliy libos', 'national costume'],
    audience: 'erkaklar',
    segment: 'milliy',
    pathUz: 'Erkaklar > Milliy > Milliy libos',
    leaf: true,
  },
  {
    id: 'erkaklar.milliy.belbog',
    labelUz: 'Belbog\'',
    synonymsUz: ['belt', 'belbog', 'milliy kamar'],
    audience: 'erkaklar',
    segment: 'milliy',
    pathUz: 'Erkaklar > Milliy > Belbog\'',
    leaf: true,
  },
  {
    id: 'erkaklar.milliy.mahsi',
    labelUz: 'Mahsi/Kalish',
    synonymsUz: ['mahsi', 'kalish', 'traditional boots', 'milliy etik'],
    audience: 'erkaklar',
    segment: 'milliy',
    pathUz: 'Erkaklar > Milliy > Mahsi/Kalish',
    leaf: true,
  },

  // ============================================
  // BOLALAR - KIYIM
  // ============================================
  {
    id: 'bolalar.kiyim.futbolka',
    labelUz: 'Futbolka',
    synonymsUz: ['t-shirt', 'ti-short', 'futbolka', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Futbolka',
    leaf: true,
  },
  {
    id: 'bolalar.kiyim.koylak',
    labelUz: 'Ko\'ylak',
    synonymsUz: ['shirt', 'ko\'ylak', 'rubashka', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Ko\'ylak',
    leaf: true,
  },
  {
    id: 'bolalar.kiyim.shim',
    labelUz: 'Shim',
    synonymsUz: ['pants', 'shim', 'bryuki', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Shim',
    leaf: true,
  },
  {
    id: 'bolalar.kiyim.jinsi',
    labelUz: 'Jinsi',
    synonymsUz: ['jeans', 'jinsi', 'dzhinsy', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Jinsi',
    leaf: true,
  },
  {
    id: 'bolalar.kiyim.platye',
    labelUz: 'Platye',
    synonymsUz: ['dress', 'platye', 'ko\'ylak', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Platye',
    leaf: true,
  },
  {
    id: 'bolalar.kiyim.pidjak',
    labelUz: 'Pidjak',
    synonymsUz: ['jacket', 'pidjak', 'kurtka', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Pidjak',
    leaf: true,
  },
  {
    id: 'bolalar.kiyim.palto',
    labelUz: 'Palto',
    synonymsUz: ['coat', 'palto', 'kurtka', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Palto',
    leaf: true,
  },
  {
    id: 'bolalar.kiyim.sviter',
    labelUz: 'Sviter',
    synonymsUz: ['sweater', 'sviter', 'jumper', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Sviter',
    leaf: true,
  },
  {
    id: 'bolalar.kiyim.xudi',
    labelUz: 'Xudi',
    synonymsUz: ['hoodie', 'xudi', 'kapshon', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Xudi',
    leaf: true,
  },
  {
    id: 'bolalar.kiyim.shorts',
    labelUz: 'Shorts',
    synonymsUz: ['shorts', 'qisqa shim', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Shorts',
    leaf: true,
  },
  {
    id: 'bolalar.kiyim.kombinezon',
    labelUz: 'Kombinezon',
    synonymsUz: ['overall', 'kombinezon', 'jumpsuit', '0-2 yosh', '2-6 yosh'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Kombinezon',
    leaf: true,
  },
  {
    id: 'bolalar.kiyim.pijama',
    labelUz: 'Pijama',
    synonymsUz: ['pajamas', 'pijama', 'nightwear', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Pijama',
    leaf: true,
  },

  // ============================================
  // BOLALAR - OYOQ KIYIM
  // ============================================
  {
    id: 'bolalar.oyoq_kiyim.krossovka',
    labelUz: 'Krossovka',
    synonymsUz: ['sneakers', 'krossovka', 'sport shoes', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'oyoq_kiyim',
    pathUz: 'Bolalar > Oyoq kiyim > Krossovka',
    leaf: true,
  },
  {
    id: 'bolalar.oyoq_kiyim.tufli',
    labelUz: 'Tufli',
    synonymsUz: ['shoes', 'tufli', 'baletka', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'oyoq_kiyim',
    pathUz: 'Bolalar > Oyoq kiyim > Tufli',
    leaf: true,
  },
  {
    id: 'bolalar.oyoq_kiyim.etik',
    labelUz: 'Etik',
    synonymsUz: ['boots', 'etik', 'butsi', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'oyoq_kiyim',
    pathUz: 'Bolalar > Oyoq kiyim > Etik',
    leaf: true,
  },
  {
    id: 'bolalar.oyoq_kiyim.sandali',
    labelUz: 'Sandali',
    synonymsUz: ['sandals', 'sandali', 'sandal', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'oyoq_kiyim',
    pathUz: 'Bolalar > Oyoq kiyim > Sandali',
    leaf: true,
  },
  {
    id: 'bolalar.oyoq_kiyim.shippak',
    labelUz: 'Shippak',
    synonymsUz: ['slippers', 'shippak', 'domashnyaya obuv', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'oyoq_kiyim',
    pathUz: 'Bolalar > Oyoq kiyim > Shippak',
    leaf: true,
  },
  {
    id: 'bolalar.oyoq_kiyim.sport_krossovka',
    labelUz: 'Sport krossovka',
    synonymsUz: ['sport shoes', 'sport krossovka', 'athletic', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'oyoq_kiyim',
    pathUz: 'Bolalar > Oyoq kiyim > Sport krossovka',
    leaf: true,
  },

  // ============================================
  // BOLALAR - AKSSESUAR
  // ============================================
  {
    id: 'bolalar.aksessuar.sumka',
    labelUz: 'Sumka',
    synonymsUz: ['bag', 'sumka', 'ryukzak', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'aksessuar',
    pathUz: 'Bolalar > Aksessuar > Sumka',
    leaf: true,
  },
  {
    id: 'bolalar.aksessuar.ryukzak',
    labelUz: 'Ryukzak',
    synonymsUz: ['backpack', 'ryukzak', 'sumka', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'aksessuar',
    pathUz: 'Bolalar > Aksessuar > Ryukzak',
    leaf: true,
  },
  {
    id: 'bolalar.aksessuar.shlyapa',
    labelUz: 'Shlyapa',
    synonymsUz: ['hat', 'shlyapa', 'kepka', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'aksessuar',
    pathUz: 'Bolalar > Aksessuar > Shlyapa',
    leaf: true,
  },
  {
    id: 'bolalar.aksessuar.kepka',
    labelUz: 'Kepka',
    synonymsUz: ['cap', 'kepka', 'baseball cap', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'aksessuar',
    pathUz: 'Bolalar > Aksessuar > Kepka',
    leaf: true,
  },
  {
    id: 'bolalar.aksessuar.qolqop',
    labelUz: 'Qo\'lqop',
    synonymsUz: ['gloves', 'qo\'lqop', 'perchatki', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'aksessuar',
    pathUz: 'Bolalar > Aksessuar > Qo\'lqop',
    leaf: true,
  },
  {
    id: 'bolalar.aksessuar.sharf',
    labelUz: 'Sharf',
    synonymsUz: ['scarf', 'sharf', 'platok', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'aksessuar',
    pathUz: 'Bolalar > Aksessuar > Sharf',
    leaf: true,
  },

  // ============================================
  // BOLALAR - ICHKI KIYIM
  // ============================================
  {
    id: 'bolalar.ichki_kiyim.paypoq',
    labelUz: 'Paypoq',
    synonymsUz: ['socks', 'paypoq', 'noski', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'ichki_kiyim',
    pathUz: 'Bolalar > Ichki kiyim > Paypoq',
    leaf: true,
  },
  {
    id: 'bolalar.ichki_kiyim.pijama',
    labelUz: 'Pijama',
    synonymsUz: ['pajamas', 'pijama', 'nightwear', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'ichki_kiyim',
    pathUz: 'Bolalar > Ichki kiyim > Pijama',
    leaf: true,
  },
  {
    id: 'bolalar.ichki_kiyim.termokiyim',
    labelUz: 'Termokiyim',
    synonymsUz: ['thermal', 'termokiyim', 'termobele', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'ichki_kiyim',
    pathUz: 'Bolalar > Ichki kiyim > Termokiyim',
    leaf: true,
  },

  // ============================================
  // BOLALAR - SPORT
  // ============================================
  {
    id: 'bolalar.sport.sport_kostyum',
    labelUz: 'Sport kostyum',
    synonymsUz: ['sport suit', 'sport kostyum', 'tracksuit', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'sport',
    pathUz: 'Bolalar > Sport > Sport kostyum',
    leaf: true,
  },
  {
    id: 'bolalar.sport.sport_futbolka',
    labelUz: 'Sport futbolka',
    synonymsUz: ['sport t-shirt', 'sport futbolka', 'athletic shirt', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'sport',
    pathUz: 'Bolalar > Sport > Sport futbolka',
    leaf: true,
  },
  {
    id: 'bolalar.sport.sport_oyoq_kiyim',
    labelUz: 'Sport oyoq kiyim',
    synonymsUz: ['sport shoes', 'sport oyoq kiyim', 'athletic', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'sport',
    pathUz: 'Bolalar > Sport > Sport oyoq kiyim',
    leaf: true,
  },

  // ============================================
  // BOLALAR - MILLIY
  // ============================================
  {
    id: 'bolalar.milliy.milliy_libos',
    labelUz: 'Milliy libos',
    synonymsUz: ['traditional dress', 'milliy libos', 'national costume', '0-2 yosh', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'milliy',
    pathUz: 'Bolalar > Milliy > Milliy libos',
    leaf: true,
  },
  {
    id: 'bolalar.milliy.doppi',
    labelUz: 'Do\'ppi',
    synonymsUz: ['do\'ppi', 'skullcap', 'milliy shlyapa', '2-6 yosh', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'milliy',
    pathUz: 'Bolalar > Milliy > Do\'ppi',
    leaf: true,
  },

  // ============================================
  // UNISEX - KIYIM
  // ============================================
  {
    id: 'unisex.kiyim.futbolka',
    labelUz: 'Futbolka',
    synonymsUz: ['t-shirt', 'ti-short', 'futbolka', 'unisex'],
    audience: 'unisex',
    segment: 'kiyim',
    pathUz: 'Barcha uchun > Kiyim > Futbolka',
    leaf: true,
  },
  {
    id: 'unisex.kiyim.xudi',
    labelUz: 'Xudi',
    synonymsUz: ['hoodie', 'xudi', 'kapshon', 'unisex'],
    audience: 'unisex',
    segment: 'kiyim',
    pathUz: 'Barcha uchun > Kiyim > Xudi',
    leaf: true,
  },
  {
    id: 'unisex.kiyim.sviter',
    labelUz: 'Sviter',
    synonymsUz: ['sweater', 'sviter', 'jumper', 'unisex'],
    audience: 'unisex',
    segment: 'kiyim',
    pathUz: 'Barcha uchun > Kiyim > Sviter',
    leaf: true,
  },
  {
    id: 'unisex.kiyim.pidjak',
    labelUz: 'Pidjak',
    synonymsUz: ['jacket', 'pidjak', 'kurtka', 'unisex'],
    audience: 'unisex',
    segment: 'kiyim',
    pathUz: 'Barcha uchun > Kiyim > Pidjak',
    leaf: true,
  },
  {
    id: 'unisex.kiyim.shorts',
    labelUz: 'Shorts',
    synonymsUz: ['shorts', 'qisqa shim', 'unisex'],
    audience: 'unisex',
    segment: 'kiyim',
    pathUz: 'Barcha uchun > Kiyim > Shorts',
    leaf: true,
  },

  // ============================================
  // UNISEX - OYOQ KIYIM
  // ============================================
  {
    id: 'unisex.oyoq_kiyim.krossovka',
    labelUz: 'Krossovka',
    synonymsUz: ['sneakers', 'krossovka', 'sport shoes', 'unisex'],
    audience: 'unisex',
    segment: 'oyoq_kiyim',
    pathUz: 'Barcha uchun > Oyoq kiyim > Krossovka',
    leaf: true,
  },
  {
    id: 'unisex.oyoq_kiyim.tufli',
    labelUz: 'Tufli',
    synonymsUz: ['shoes', 'tufli', 'unisex'],
    audience: 'unisex',
    segment: 'oyoq_kiyim',
    pathUz: 'Barcha uchun > Oyoq kiyim > Tufli',
    leaf: true,
  },
  {
    id: 'unisex.oyoq_kiyim.etik',
    labelUz: 'Etik',
    synonymsUz: ['boots', 'etik', 'butsi', 'unisex'],
    audience: 'unisex',
    segment: 'oyoq_kiyim',
    pathUz: 'Barcha uchun > Oyoq kiyim > Etik',
    leaf: true,
  },
  {
    id: 'unisex.oyoq_kiyim.sandali',
    labelUz: 'Sandali',
    synonymsUz: ['sandals', 'sandali', 'sandal', 'unisex'],
    audience: 'unisex',
    segment: 'oyoq_kiyim',
    pathUz: 'Barcha uchun > Oyoq kiyim > Sandali',
    leaf: true,
  },

  // ============================================
  // UNISEX - AKSSESUAR
  // ============================================
  {
    id: 'unisex.aksessuar.sumka',
    labelUz: 'Sumka',
    synonymsUz: ['bag', 'sumka', 'ryukzak', 'unisex'],
    audience: 'unisex',
    segment: 'aksessuar',
    pathUz: 'Barcha uchun > Aksessuar > Sumka',
    leaf: true,
  },
  {
    id: 'unisex.aksessuar.ryukzak',
    labelUz: 'Ryukzak',
    synonymsUz: ['backpack', 'ryukzak', 'sumka', 'unisex'],
    audience: 'unisex',
    segment: 'aksessuar',
    pathUz: 'Barcha uchun > Aksessuar > Ryukzak',
    leaf: true,
  },
  {
    id: 'unisex.aksessuar.kamar',
    labelUz: 'Kamar',
    synonymsUz: ['belt', 'kamar', 'remen', 'unisex'],
    audience: 'unisex',
    segment: 'aksessuar',
    pathUz: 'Barcha uchun > Aksessuar > Kamar',
    leaf: true,
  },
  {
    id: 'unisex.aksessuar.shlyapa',
    labelUz: 'Shlyapa',
    synonymsUz: ['hat', 'shlyapa', 'kepka', 'unisex'],
    audience: 'unisex',
    segment: 'aksessuar',
    pathUz: 'Barcha uchun > Aksessuar > Shlyapa',
    leaf: true,
  },
  {
    id: 'unisex.aksessuar.kepka',
    labelUz: 'Kepka',
    synonymsUz: ['cap', 'kepka', 'baseball cap', 'unisex'],
    audience: 'unisex',
    segment: 'aksessuar',
    pathUz: 'Barcha uchun > Aksessuar > Kepka',
    leaf: true,
  },
  {
    id: 'unisex.aksessuar.qolqop',
    labelUz: 'Qo\'lqop',
    synonymsUz: ['gloves', 'qo\'lqop', 'perchatki', 'unisex'],
    audience: 'unisex',
    segment: 'aksessuar',
    pathUz: 'Barcha uchun > Aksessuar > Qo\'lqop',
    leaf: true,
  },
  {
    id: 'unisex.aksessuar.sharf',
    labelUz: 'Sharf',
    synonymsUz: ['scarf', 'sharf', 'platok', 'unisex'],
    audience: 'unisex',
    segment: 'aksessuar',
    pathUz: 'Barcha uchun > Aksessuar > Sharf',
    leaf: true,
  },
  {
    id: 'unisex.aksessuar.hamyon',
    labelUz: 'Hamyon',
    synonymsUz: ['wallet', 'hamyon', 'koshelek', 'unisex'],
    audience: 'unisex',
    segment: 'aksessuar',
    pathUz: 'Barcha uchun > Aksessuar > Hamyon',
    leaf: true,
  },

  // ============================================
  // UNISEX - ICHKI KIYIM
  // ============================================
  {
    id: 'unisex.ichki_kiyim.paypoq',
    labelUz: 'Paypoq',
    synonymsUz: ['socks', 'paypoq', 'noski', 'unisex'],
    audience: 'unisex',
    segment: 'ichki_kiyim',
    pathUz: 'Barcha uchun > Ichki kiyim > Paypoq',
    leaf: true,
  },
  {
    id: 'unisex.ichki_kiyim.termokiyim',
    labelUz: 'Termokiyim',
    synonymsUz: ['thermal', 'termokiyim', 'termobele', 'unisex'],
    audience: 'unisex',
    segment: 'ichki_kiyim',
    pathUz: 'Barcha uchun > Ichki kiyim > Termokiyim',
    leaf: true,
  },

  // ============================================
  // UNISEX - SPORT
  // ============================================
  {
    id: 'unisex.sport.sport_kostyum',
    labelUz: 'Sport kostyum',
    synonymsUz: ['sport suit', 'sport kostyum', 'tracksuit', 'unisex'],
    audience: 'unisex',
    segment: 'sport',
    pathUz: 'Barcha uchun > Sport > Sport kostyum',
    leaf: true,
  },
  {
    id: 'unisex.sport.sport_futbolka',
    labelUz: 'Sport futbolka',
    synonymsUz: ['sport t-shirt', 'sport futbolka', 'athletic shirt', 'unisex'],
    audience: 'unisex',
    segment: 'sport',
    pathUz: 'Barcha uchun > Sport > Sport futbolka',
    leaf: true,
  },
  {
    id: 'unisex.sport.trening_oyoq_kiyim',
    labelUz: 'Trening oyoq kiyim',
    synonymsUz: ['training shoes', 'trening', 'workout shoes', 'unisex'],
    audience: 'unisex',
    segment: 'sport',
    pathUz: 'Barcha uchun > Sport > Trening oyoq kiyim',
    leaf: true,
  },

  // ============================================
  // YANGI DETALLAR - USTKI KIYIMLAR
  // ============================================
  {
    id: 'ayollar.kiyim.trench',
    labelUz: 'Trench / Plash',
    synonymsUz: ['trench coat', 'plash', 'trench', 'dojdeviy'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Trench / Plash',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.kojanka',
    labelUz: 'Charm kurtka (Kojanka)',
    synonymsUz: ['leather jacket', 'kojanka', 'charm kurtka', 'koja'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Charm kurtka (Kojanka)',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.bomber',
    labelUz: 'Bomber',
    synonymsUz: ['bomber jacket', 'bomber', 'aviator'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Bomber',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.jinsi_kurtka',
    labelUz: 'Jinsi kurtka',
    synonymsUz: ['denim jacket', 'jinsi kurtka', 'jeans jacket'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Jinsi kurtka',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.jilet',
    labelUz: 'Jilet (Nimcha)',
    synonymsUz: ['vest', 'jilet', 'nimcha', 'bezrukavka'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Jilet (Nimcha)',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.parka',
    labelUz: 'Parka',
    synonymsUz: ['parka', 'winter jacket', 'qishki kurtka'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Parka',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.dublyonka',
    labelUz: 'Dublyonka',
    synonymsUz: ['double-breasted coat', 'dublyonka', 'ikki tugmali palto'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Dublyonka',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.shuba',
    labelUz: 'Mo\'yna po\'stin (Shuba)',
    synonymsUz: ['fur coat', 'shuba', 'mo\'yna po\'stin', 'fur'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Mo\'yna po\'stin (Shuba)',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.dojdeviy',
    labelUz: 'Yomg\'irpo\'sh',
    synonymsUz: ['raincoat', 'dojdeviy', 'yomg\'irpo\'sh', 'rain jacket'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Yomg\'irpo\'sh',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.vetrovka',
    labelUz: 'Vetrovka',
    synonymsUz: ['windbreaker', 'vetrovka', 'shamol kurtka'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Vetrovka',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.trench',
    labelUz: 'Trench / Plash',
    synonymsUz: ['trench coat', 'plash', 'trench', 'dojdeviy'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Trench / Plash',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.kojanka',
    labelUz: 'Charm kurtka (Kojanka)',
    synonymsUz: ['leather jacket', 'kojanka', 'charm kurtka', 'koja'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Charm kurtka (Kojanka)',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.bomber',
    labelUz: 'Bomber',
    synonymsUz: ['bomber jacket', 'bomber', 'aviator'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Bomber',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.jinsi_kurtka',
    labelUz: 'Jinsi kurtka',
    synonymsUz: ['denim jacket', 'jinsi kurtka', 'jeans jacket'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Jinsi kurtka',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.jilet',
    labelUz: 'Jilet (Nimcha)',
    synonymsUz: ['vest', 'jilet', 'nimcha', 'bezrukavka'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Jilet (Nimcha)',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.parka',
    labelUz: 'Parka',
    synonymsUz: ['parka', 'winter jacket', 'qishki kurtka'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Parka',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.dublyonka',
    labelUz: 'Dublyonka',
    synonymsUz: ['double-breasted coat', 'dublyonka', 'ikki tugmali palto'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Dublyonka',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.shuba',
    labelUz: 'Mo\'yna po\'stin (Shuba)',
    synonymsUz: ['fur coat', 'shuba', 'mo\'yna po\'stin', 'fur'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Mo\'yna po\'stin (Shuba)',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.dojdeviy',
    labelUz: 'Yomg\'irpo\'sh',
    synonymsUz: ['raincoat', 'dojdeviy', 'yomg\'irpo\'sh', 'rain jacket'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Yomg\'irpo\'sh',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.vetrovka',
    labelUz: 'Vetrovka',
    synonymsUz: ['windbreaker', 'vetrovka', 'shamol kurtka'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Vetrovka',
    leaf: true,
  },

  // ============================================
  // YANGI DETALLAR - YENGIL KIYIMLAR
  // ============================================
  {
    id: 'ayollar.kiyim.futbolka_polo',
    labelUz: 'Polo futbolka',
    synonymsUz: ['polo shirt', 'polo futbolka', 'polo'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Polo futbolka',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.longsliv',
    labelUz: 'Longsliv (Uzun yengli futbolka)',
    synonymsUz: ['long sleeve', 'longsliv', 'uzun yengli futbolka'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Longsliv (Uzun yengli futbolka)',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.vodolazka',
    labelUz: 'Vodolazka',
    synonymsUz: ['turtleneck', 'vodolazka', 'vysokiy vorotnik'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Vodolazka',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.kroy_top',
    labelUz: 'Krop-top',
    synonymsUz: ['crop top', 'kroy-top', 'qisqa futbolka'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Krop-top',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.rubashka_klassik',
    labelUz: 'Klassik ko\'ylak',
    synonymsUz: ['classic shirt', 'rubashka klassik', 'formal shirt'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Klassik ko\'ylak',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.rubashka_casual',
    labelUz: 'Kundalik ko\'ylak (Katak)',
    synonymsUz: ['casual shirt', 'rubashka casual', 'katak', 'flannel'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Kundalik ko\'ylak (Katak)',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.svitshot',
    labelUz: 'Svitshot',
    synonymsUz: ['sweatshirt', 'svitshot', 'sportivnaya futbolka'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Svitshot',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.tolstovka',
    labelUz: 'Tolstovka (Zamokli)',
    synonymsUz: ['zip-up hoodie', 'tolstovka', 'zamokli xudi'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Tolstovka (Zamokli)',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.futbolka_polo',
    labelUz: 'Polo futbolka',
    synonymsUz: ['polo shirt', 'polo futbolka', 'polo'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Polo futbolka',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.longsliv',
    labelUz: 'Longsliv (Uzun yengli futbolka)',
    synonymsUz: ['long sleeve', 'longsliv', 'uzun yengli futbolka'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Longsliv (Uzun yengli futbolka)',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.vodolazka',
    labelUz: 'Vodolazka',
    synonymsUz: ['turtleneck', 'vodolazka', 'vysokiy vorotnik'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Vodolazka',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.rubashka_klassik',
    labelUz: 'Klassik ko\'ylak',
    synonymsUz: ['classic shirt', 'rubashka klassik', 'formal shirt'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Klassik ko\'ylak',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.rubashka_casual',
    labelUz: 'Kundalik ko\'ylak (Katak)',
    synonymsUz: ['casual shirt', 'rubashka casual', 'katak', 'flannel'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Kundalik ko\'ylak (Katak)',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.svitshot',
    labelUz: 'Svitshot',
    synonymsUz: ['sweatshirt', 'svitshot', 'sportivnaya futbolka'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Svitshot',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.tolstovka',
    labelUz: 'Tolstovka (Zamokli)',
    synonymsUz: ['zip-up hoodie', 'tolstovka', 'zamokli xudi'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Tolstovka (Zamokli)',
    leaf: true,
  },

  // ============================================
  // YANGI DETALLAR - SHIM VA YUBKALAR
  // ============================================
  {
    id: 'ayollar.kiyim.jinsi_skinny',
    labelUz: 'Skinny Jinsi',
    synonymsUz: ['skinny jeans', 'jinsi skinny', 'tor jinsi'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Skinny Jinsi',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.jinsi_mom',
    labelUz: 'Mom Jeans',
    synonymsUz: ['mom jeans', 'jinsi mom', 'klassik jinsi'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Mom Jeans',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.jinsi_wide',
    labelUz: 'Keng Jinsi (Wide Leg)',
    synonymsUz: ['wide leg jeans', 'jinsi wide', 'keng jinsi'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Keng Jinsi (Wide Leg)',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.shim_klassik',
    labelUz: 'Klassik shim',
    synonymsUz: ['classic pants', 'shim klassik', 'straight pants'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Klassik shim',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.shim_chinos',
    labelUz: 'Chinos shim',
    synonymsUz: ['chinos', 'shim chinos', 'chino pants'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Chinos shim',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.shim_kargo',
    labelUz: 'Kargo shim (Cho\'ntakli)',
    synonymsUz: ['cargo pants', 'shim kargo', 'cho\'ntakli shim'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Kargo shim (Cho\'ntakli)',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.shim_sport',
    labelUz: 'Sportivka',
    synonymsUz: ['sport pants', 'shim sport', 'sportivka'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Sportivka',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.legginsy',
    labelUz: 'Losina / Legginsy',
    synonymsUz: ['leggings', 'legginsy', 'losina', 'tayt'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Losina / Legginsy',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.shortik_jinsi',
    labelUz: 'Jinsi shortik',
    synonymsUz: ['denim shorts', 'shortik jinsi', 'jinsi shorts'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Jinsi shortik',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.shortik_sport',
    labelUz: 'Sport shortik',
    synonymsUz: ['sport shorts', 'shortik sport', 'athletic shorts'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Sport shortik',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.shortik_klassik',
    labelUz: 'Bermuda / Klassik shortik',
    synonymsUz: ['bermuda shorts', 'shortik klassik', 'bermuda'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Bermuda / Klassik shortik',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.yubka_mini',
    labelUz: 'Mini yubka',
    synonymsUz: ['mini skirt', 'yubka mini', 'qisqa yubka'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Mini yubka',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.yubka_midi',
    labelUz: 'Midi yubka',
    synonymsUz: ['midi skirt', 'yubka midi', 'o\'rta yubka'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Midi yubka',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.yubka_maxi',
    labelUz: 'Maxi (Uzun) yubka',
    synonymsUz: ['maxi skirt', 'yubka maxi', 'uzun yubka'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Maxi (Uzun) yubka',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.yubka_qalam',
    labelUz: 'Qalam yubka (Pencil)',
    synonymsUz: ['pencil skirt', 'yubka qalam', 'pencil'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Qalam yubka (Pencil)',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.yubka_pile',
    labelUz: 'Pile yubka',
    synonymsUz: ['pleated skirt', 'yubka pile', 'skladki'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Pile yubka',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.jinsi_skinny',
    labelUz: 'Skinny Jinsi',
    synonymsUz: ['skinny jeans', 'jinsi skinny', 'tor jinsi'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Skinny Jinsi',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.jinsi_mom',
    labelUz: 'Mom Jeans',
    synonymsUz: ['mom jeans', 'jinsi mom', 'klassik jinsi'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Mom Jeans',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.jinsi_wide',
    labelUz: 'Keng Jinsi (Wide Leg)',
    synonymsUz: ['wide leg jeans', 'jinsi wide', 'keng jinsi'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Keng Jinsi (Wide Leg)',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.shim_klassik',
    labelUz: 'Klassik shim',
    synonymsUz: ['classic pants', 'shim klassik', 'straight pants'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Klassik shim',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.shim_chinos',
    labelUz: 'Chinos shim',
    synonymsUz: ['chinos', 'shim chinos', 'chino pants'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Chinos shim',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.shim_kargo',
    labelUz: 'Kargo shim (Cho\'ntakli)',
    synonymsUz: ['cargo pants', 'shim kargo', 'cho\'ntakli shim'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Kargo shim (Cho\'ntakli)',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.shim_sport',
    labelUz: 'Sportivka',
    synonymsUz: ['sport pants', 'shim sport', 'sportivka'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Sportivka',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.shortik_jinsi',
    labelUz: 'Jinsi shortik',
    synonymsUz: ['denim shorts', 'shortik jinsi', 'jinsi shorts'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Jinsi shortik',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.shortik_sport',
    labelUz: 'Sport shortik',
    synonymsUz: ['sport shorts', 'shortik sport', 'athletic shorts'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Sport shortik',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.shortik_klassik',
    labelUz: 'Bermuda / Klassik shortik',
    synonymsUz: ['bermuda shorts', 'shortik klassik', 'bermuda'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Bermuda / Klassik shortik',
    leaf: true,
  },

  // ============================================
  // YANGI DETALLAR - AYOLLAR LIBOSLARI
  // ============================================
  {
    id: 'ayollar.kiyim.koylak_oqshom',
    labelUz: 'Oqshom libosi (Vecherniy)',
    synonymsUz: ['evening dress', 'koylak oqshom', 'vecherniy', 'formal dress'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Oqshom libosi (Vecherniy)',
    leaf: true,
    requiredFieldsOverride: ['brand', 'size', 'condition', 'price'],
    suggestedFields: ['material', 'color', 'occasion', 'length'],
  },
  {
    id: 'ayollar.kiyim.koylak_kundalik',
    labelUz: 'Kundalik ko\'ylak',
    synonymsUz: ['casual dress', 'koylak kundalik', 'everyday dress'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Kundalik ko\'ylak',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.koylak_kokteyl',
    labelUz: 'Kokteyl ko\'ylak',
    synonymsUz: ['cocktail dress', 'koylak kokteyl', 'cocktail'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Kokteyl ko\'ylak',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.koylak_ofis',
    labelUz: 'Ofis ko\'ylagi',
    synonymsUz: ['office dress', 'koylak ofis', 'business dress'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Ofis ko\'ylagi',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.kostyum_ayollar',
    labelUz: 'Ayollar kostyumi (Ikki qismli)',
    synonymsUz: ['women suit', 'kostyum ayollar', 'two-piece suit'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Ayollar kostyumi (Ikki qismli)',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.kostyum_erkaklar',
    labelUz: 'Erkaklar kostyumi (Troyka/Dvoyka)',
    synonymsUz: ['men suit', 'kostyum erkaklar', 'troyka', 'dvoyka', 'three-piece', 'two-piece'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Erkaklar kostyumi (Troyka/Dvoyka)',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.smoking',
    labelUz: 'Smoking',
    synonymsUz: ['tuxedo', 'smoking', 'formal suit'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Smoking',
    leaf: true,
  },

  // ============================================
  // YANGI DETALLAR - OYOQ KIYIMLAR
  // ============================================
  {
    id: 'ayollar.oyoq_kiyim.krossovka_kundalik',
    labelUz: 'Kundalik krossovka (Sneakers)',
    synonymsUz: ['casual sneakers', 'krossovka kundalik', 'sneakers'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Kundalik krossovka (Sneakers)',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.keda',
    labelUz: 'Keda (Konvers)',
    synonymsUz: ['converse', 'keda', 'konvers', 'all-star'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Keda (Konvers)',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.oksford',
    labelUz: 'Oksford (Klassik)',
    synonymsUz: ['oxford shoes', 'oksford', 'klassik tufli'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Oksford (Klassik)',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.derbi',
    labelUz: 'Derbi',
    synonymsUz: ['derby shoes', 'derbi', 'open lacing'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Derbi',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.bosonojka',
    labelUz: 'Bosonojka',
    synonymsUz: ['flats', 'bosonojka', 'baletka'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Bosonojka',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.sabo',
    labelUz: 'Sabo (Crocs)',
    synonymsUz: ['crocs', 'sabo', 'rubber shoes'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Sabo (Crocs)',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.etik_qishki',
    labelUz: 'Qishki etik (Sapog)',
    synonymsUz: ['winter boots', 'etik qishki', 'sapog', 'qishki butsi'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Qishki etik (Sapog)',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.botford',
    labelUz: 'Botfort (Uzun etik)',
    synonymsUz: ['boots', 'botford', 'uzun etik', 'high boots'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Botfort (Uzun etik)',
    leaf: true,
  },
  {
    id: 'ayollar.oyoq_kiyim.chelsy',
    labelUz: 'Chelsi',
    synonymsUz: ['chelsea boots', 'chelsy', 'ankle boots'],
    audience: 'ayollar',
    segment: 'oyoq_kiyim',
    pathUz: 'Ayollar > Oyoq kiyim > Chelsi',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.krossovka_kundalik',
    labelUz: 'Kundalik krossovka (Sneakers)',
    synonymsUz: ['casual sneakers', 'krossovka kundalik', 'sneakers'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Kundalik krossovka (Sneakers)',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.keda',
    labelUz: 'Keda (Konvers)',
    synonymsUz: ['converse', 'keda', 'konvers', 'all-star'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Keda (Konvers)',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.oksford',
    labelUz: 'Oksford (Klassik)',
    synonymsUz: ['oxford shoes', 'oksford', 'klassik tufli'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Oksford (Klassik)',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.derbi',
    labelUz: 'Derbi',
    synonymsUz: ['derby shoes', 'derbi', 'open lacing'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Derbi',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.sabo',
    labelUz: 'Sabo (Crocs)',
    synonymsUz: ['crocs', 'sabo', 'rubber shoes'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Sabo (Crocs)',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.etik_qishki',
    labelUz: 'Qishki etik (Sapog)',
    synonymsUz: ['winter boots', 'etik qishki', 'sapog', 'qishki butsi'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Qishki etik (Sapog)',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.botford',
    labelUz: 'Botfort (Uzun etik)',
    synonymsUz: ['boots', 'botford', 'uzun etik', 'high boots'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Botfort (Uzun etik)',
    leaf: true,
  },
  {
    id: 'erkaklar.oyoq_kiyim.chelsy',
    labelUz: 'Chelsi',
    synonymsUz: ['chelsea boots', 'chelsy', 'ankle boots'],
    audience: 'erkaklar',
    segment: 'oyoq_kiyim',
    pathUz: 'Erkaklar > Oyoq kiyim > Chelsi',
    leaf: true,
  },

  // ============================================
  // YANGI DETALLAR - AKSSESUARLAR
  // ============================================
  {
    id: 'ayollar.aksessuar.sumka_shopper',
    labelUz: 'Shopper sumka',
    synonymsUz: ['shopper bag', 'sumka shopper', 'tote bag'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Shopper sumka',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.sumka_klatch',
    labelUz: 'Klatch',
    synonymsUz: ['clutch', 'klatch', 'evening bag'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Klatch',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.sumka_krossbodi',
    labelUz: 'Krossbodi sumka',
    synonymsUz: ['crossbody bag', 'sumka krossbodi', 'shoulder bag'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Krossbodi sumka',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.borsetka',
    labelUz: 'Borsetka',
    synonymsUz: ['purse', 'borsetka', 'small bag'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Borsetka',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.chamadon',
    labelUz: 'Chamadon',
    synonymsUz: ['suitcase', 'chamadon', 'travel bag'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Chamadon',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.babochka',
    labelUz: 'Babochka',
    synonymsUz: ['bow tie', 'babochka', 'galstuk'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Babochka',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.panama',
    labelUz: 'Panama',
    synonymsUz: ['panama hat', 'panama', 'shlyapa'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Panama',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.shapka',
    labelUz: 'Qishki shapka (Beanie)',
    synonymsUz: ['beanie', 'shapka', 'qishki shapka', 'winter hat'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Qishki shapka (Beanie)',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.romol',
    labelUz: 'Ro\'mol',
    synonymsUz: ['handkerchief', 'romol', 'platok'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Ro\'mol',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.kozoynak_quyosh',
    labelUz: 'Quyosh ko\'zoynagi',
    synonymsUz: ['sunglasses', 'kozoynak quyosh', 'sun glasses'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Quyosh ko\'zoynagi',
    leaf: true,
  },
  {
    id: 'ayollar.aksessuar.zargarlik',
    labelUz: 'Zargarlik buyumlari (Bijuteriya)',
    synonymsUz: ['jewelry', 'zargarlik', 'bijuteriya', 'accessories'],
    audience: 'ayollar',
    segment: 'aksessuar',
    pathUz: 'Ayollar > Aksessuar > Zargarlik buyumlari (Bijuteriya)',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.sumka_shopper',
    labelUz: 'Shopper sumka',
    synonymsUz: ['shopper bag', 'sumka shopper', 'tote bag'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Shopper sumka',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.chamadon',
    labelUz: 'Chamadon',
    synonymsUz: ['suitcase', 'chamadon', 'travel bag'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Chamadon',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.babochka',
    labelUz: 'Babochka',
    synonymsUz: ['bow tie', 'babochka', 'galstuk'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Babochka',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.panama',
    labelUz: 'Panama',
    synonymsUz: ['panama hat', 'panama', 'shlyapa'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Panama',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.shapka',
    labelUz: 'Qishki shapka (Beanie)',
    synonymsUz: ['beanie', 'shapka', 'qishki shapka', 'winter hat'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Qishki shapka (Beanie)',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.romol',
    labelUz: 'Ro\'mol',
    synonymsUz: ['handkerchief', 'romol', 'platok'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Ro\'mol',
    leaf: true,
  },
  {
    id: 'erkaklar.aksessuar.kozoynak_quyosh',
    labelUz: 'Quyosh ko\'zoynagi',
    synonymsUz: ['sunglasses', 'kozoynak quyosh', 'sun glasses'],
    audience: 'erkaklar',
    segment: 'aksessuar',
    pathUz: 'Erkaklar > Aksessuar > Quyosh ko\'zoynagi',
    leaf: true,
  },

  // ============================================
  // YANGI DETALLAR - ICHKI VA UY KIYIMLARI
  // ============================================
  {
    id: 'ayollar.ichki_kiyim.trusi',
    labelUz: 'Ichki kiyim (Trusi)',
    synonymsUz: ['underwear', 'trusi', 'ichki kiyim', 'panties'],
    audience: 'ayollar',
    segment: 'ichki_kiyim',
    pathUz: 'Ayollar > Ichki kiyim > Ichki kiyim (Trusi)',
    leaf: true,
  },
  {
    id: 'ayollar.ichki_kiyim.byustgalter',
    labelUz: 'Byustgalter',
    synonymsUz: ['bra', 'byustgalter', 'sutyen'],
    audience: 'ayollar',
    segment: 'ichki_kiyim',
    pathUz: 'Ayollar > Ichki kiyim > Byustgalter',
    leaf: true,
  },
  {
    id: 'ayollar.ichki_kiyim.xalat',
    labelUz: 'Xalat',
    synonymsUz: ['robe', 'xalat', 'bathrobe', 'domashnyaya odejda'],
    audience: 'ayollar',
    segment: 'ichki_kiyim',
    pathUz: 'Ayollar > Ichki kiyim > Xalat',
    leaf: true,
  },
  {
    id: 'ayollar.ichki_kiyim.paypoq_uzun',
    labelUz: 'Uzun paypoq',
    synonymsUz: ['long socks', 'paypoq uzun', 'knee socks'],
    audience: 'ayollar',
    segment: 'ichki_kiyim',
    pathUz: 'Ayollar > Ichki kiyim > Uzun paypoq',
    leaf: true,
  },
  {
    id: 'ayollar.ichki_kiyim.paypoq_kalta',
    labelUz: 'Kalta paypoq',
    synonymsUz: ['short socks', 'paypoq kalta', 'ankle socks'],
    audience: 'ayollar',
    segment: 'ichki_kiyim',
    pathUz: 'Ayollar > Ichki kiyim > Kalta paypoq',
    leaf: true,
  },
  {
    id: 'ayollar.ichki_kiyim.sledki',
    labelUz: 'Sledki',
    synonymsUz: ['slippers', 'sledki', 'domashnyaya obuv'],
    audience: 'ayollar',
    segment: 'ichki_kiyim',
    pathUz: 'Ayollar > Ichki kiyim > Sledki',
    leaf: true,
  },
  {
    id: 'ayollar.ichki_kiyim.kupalnik',
    labelUz: 'Cho\'milish kiyimi (Kupalnik)',
    synonymsUz: ['swimsuit', 'kupalnik', 'bathing suit', 'bikini'],
    audience: 'ayollar',
    segment: 'ichki_kiyim',
    pathUz: 'Ayollar > Ichki kiyim > Cho\'milish kiyimi (Kupalnik)',
    leaf: true,
  },
  {
    id: 'ayollar.ichki_kiyim.plavki',
    labelUz: 'Plavki',
    synonymsUz: ['swim trunks', 'plavki', 'swimming shorts'],
    audience: 'ayollar',
    segment: 'ichki_kiyim',
    pathUz: 'Ayollar > Ichki kiyim > Plavki',
    leaf: true,
  },
  {
    id: 'erkaklar.ichki_kiyim.trusi',
    labelUz: 'Ichki kiyim (Trusi)',
    synonymsUz: ['underwear', 'trusi', 'ichki kiyim', 'boxers'],
    audience: 'erkaklar',
    segment: 'ichki_kiyim',
    pathUz: 'Erkaklar > Ichki kiyim > Ichki kiyim (Trusi)',
    leaf: true,
  },
  {
    id: 'erkaklar.ichki_kiyim.xalat',
    labelUz: 'Xalat',
    synonymsUz: ['robe', 'xalat', 'bathrobe', 'domashnyaya odejda'],
    audience: 'erkaklar',
    segment: 'ichki_kiyim',
    pathUz: 'Erkaklar > Ichki kiyim > Xalat',
    leaf: true,
  },
  {
    id: 'erkaklar.ichki_kiyim.paypoq_uzun',
    labelUz: 'Uzun paypoq',
    synonymsUz: ['long socks', 'paypoq uzun', 'knee socks'],
    audience: 'erkaklar',
    segment: 'ichki_kiyim',
    pathUz: 'Erkaklar > Ichki kiyim > Uzun paypoq',
    leaf: true,
  },
  {
    id: 'erkaklar.ichki_kiyim.paypoq_kalta',
    labelUz: 'Kalta paypoq',
    synonymsUz: ['short socks', 'paypoq kalta', 'ankle socks'],
    audience: 'erkaklar',
    segment: 'ichki_kiyim',
    pathUz: 'Erkaklar > Ichki kiyim > Kalta paypoq',
    leaf: true,
  },
  {
    id: 'erkaklar.ichki_kiyim.plavki',
    labelUz: 'Plavki',
    synonymsUz: ['swim trunks', 'plavki', 'swimming shorts'],
    audience: 'erkaklar',
    segment: 'ichki_kiyim',
    pathUz: 'Erkaklar > Ichki kiyim > Plavki',
    leaf: true,
  },

  // ============================================
  // YANGI DETALLAR - BOLALAR UCHUN MAXSUS
  // ============================================
  {
    id: 'bolalar.kiyim.bodik',
    labelUz: 'Bodik',
    synonymsUz: ['bodysuit', 'bodik', '0-2 yosh', 'chaqaloq'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Bodik',
    leaf: true,
  },
  {
    id: 'bolalar.kiyim.slunyavchik',
    labelUz: 'Slunyavchik',
    synonymsUz: ['bib', 'slunyavchik', '0-2 yosh', 'chaqaloq'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Slunyavchik',
    leaf: true,
  },
  {
    id: 'bolalar.kiyim.polzunki',
    labelUz: 'Polzunki',
    synonymsUz: ['crawling suit', 'polzunki', '0-2 yosh', 'chaqaloq'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Polzunki',
    leaf: true,
  },
  {
    id: 'bolalar.kiyim.konvert',
    labelUz: 'Konvert (Chaqaloqlar uchun)',
    synonymsUz: ['swaddle', 'konvert', '0-2 yosh', 'chaqaloq'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Konvert (Chaqaloqlar uchun)',
    leaf: true,
  },
  {
    id: 'bolalar.kiyim.maktab_formasi',
    labelUz: 'Maktab formasi',
    synonymsUz: ['school uniform', 'maktab formasi', '7-12 yosh', '13-17 yosh'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Maktab formasi',
    leaf: true,
  },
  {
    id: 'bolalar.kiyim.karnaval_kiyim',
    labelUz: 'Karnaval / Bayram kiyimi',
    synonymsUz: ['carnival costume', 'karnaval kiyim', '2-6 yosh', '7-12 yosh'],
    audience: 'bolalar',
    segment: 'kiyim',
    pathUz: 'Bolalar > Kiyim > Karnaval / Bayram kiyimi',
    leaf: true,
  },

  // ============================================
  // YANGI DETALLAR - MILLIY KIYIMLAR
  // ============================================
  {
    id: 'ayollar.milliy.yaktak',
    labelUz: 'Yaktak',
    synonymsUz: ['yaktak', 'traditional dress', 'milliy kiyim'],
    audience: 'ayollar',
    segment: 'milliy',
    pathUz: 'Ayollar > Milliy > Yaktak',
    leaf: true,
  },
  {
    id: 'ayollar.milliy.kavush',
    labelUz: 'Kavush',
    synonymsUz: ['kavush', 'traditional shoes', 'milliy oyoq kiyim'],
    audience: 'ayollar',
    segment: 'milliy',
    pathUz: 'Ayollar > Milliy > Kavush',
    leaf: true,
  },
  {
    id: 'ayollar.milliy.kelin_sarpo',
    labelUz: 'Kelin sarpo',
    synonymsUz: ['bridal outfit', 'kelin sarpo', 'milliy to\'y kiyimi'],
    audience: 'ayollar',
    segment: 'milliy',
    pathUz: 'Ayollar > Milliy > Kelin sarpo',
    leaf: true,
  },
  {
    id: 'erkaklar.milliy.yaktak',
    labelUz: 'Yaktak',
    synonymsUz: ['yaktak', 'traditional dress', 'milliy kiyim'],
    audience: 'erkaklar',
    segment: 'milliy',
    pathUz: 'Erkaklar > Milliy > Yaktak',
    leaf: true,
  },
  {
    id: 'erkaklar.milliy.kavush',
    labelUz: 'Kavush',
    synonymsUz: ['kavush', 'traditional shoes', 'milliy oyoq kiyim'],
    audience: 'erkaklar',
    segment: 'milliy',
    pathUz: 'Erkaklar > Milliy > Kavush',
    leaf: true,
  },
  {
    id: 'bolalar.milliy.yaktak',
    labelUz: 'Yaktak',
    synonymsUz: ['yaktak', 'traditional dress', 'milliy kiyim', '2-6 yosh', '7-12 yosh'],
    audience: 'bolalar',
    segment: 'milliy',
    pathUz: 'Bolalar > Milliy > Yaktak',
    leaf: true,
  },

  // ============================================
  // YANGI DETALLAR - SPORT VA MAXSUS
  // ============================================
  {
    id: 'ayollar.sport.kimono',
    labelUz: 'Kimono (Dzyudo/Karate)',
    synonymsUz: ['kimono', 'dzyudo', 'karate', 'martial arts'],
    audience: 'ayollar',
    segment: 'sport',
    pathUz: 'Ayollar > Sport > Kimono (Dzyudo/Karate)',
    leaf: true,
  },
  {
    id: 'ayollar.sport.rashgard',
    labelUz: 'Rashgard',
    synonymsUz: ['rashguard', 'rashgard', 'sport top'],
    audience: 'ayollar',
    segment: 'sport',
    pathUz: 'Ayollar > Sport > Rashgard',
    leaf: true,
  },
  {
    id: 'ayollar.sport.forma_futbol',
    labelUz: 'Futbol formasi',
    synonymsUz: ['football jersey', 'forma futbol', 'soccer jersey'],
    audience: 'ayollar',
    segment: 'sport',
    pathUz: 'Ayollar > Sport > Futbol formasi',
    leaf: true,
  },
  {
    id: 'erkaklar.sport.kimono',
    labelUz: 'Kimono (Dzyudo/Karate)',
    synonymsUz: ['kimono', 'dzyudo', 'karate', 'martial arts'],
    audience: 'erkaklar',
    segment: 'sport',
    pathUz: 'Erkaklar > Sport > Kimono (Dzyudo/Karate)',
    leaf: true,
  },
  {
    id: 'erkaklar.sport.rashgard',
    labelUz: 'Rashgard',
    synonymsUz: ['rashguard', 'rashgard', 'sport top'],
    audience: 'erkaklar',
    segment: 'sport',
    pathUz: 'Erkaklar > Sport > Rashgard',
    leaf: true,
  },
  {
    id: 'erkaklar.sport.forma_futbol',
    labelUz: 'Futbol formasi',
    synonymsUz: ['football jersey', 'forma futbol', 'soccer jersey'],
    audience: 'erkaklar',
    segment: 'sport',
    pathUz: 'Erkaklar > Sport > Futbol formasi',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.maxsus_kiyim',
    labelUz: 'Ish kiyimi (Uniformalar)',
    synonymsUz: ['work uniform', 'maxsus kiyim', 'uniforma', 'ish kiyimi'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Ish kiyimi (Uniformalar)',
    leaf: true,
  },
  {
    id: 'ayollar.kiyim.tibbiyot_xalat',
    labelUz: 'Tibbiyot xalati',
    synonymsUz: ['medical coat', 'tibbiyot xalat', 'doctor coat'],
    audience: 'ayollar',
    segment: 'kiyim',
    pathUz: 'Ayollar > Kiyim > Tibbiyot xalati',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.maxsus_kiyim',
    labelUz: 'Ish kiyimi (Uniformalar)',
    synonymsUz: ['work uniform', 'maxsus kiyim', 'uniforma', 'ish kiyimi'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Ish kiyimi (Uniformalar)',
    leaf: true,
  },
  {
    id: 'erkaklar.kiyim.tibbiyot_xalat',
    labelUz: 'Tibbiyot xalati',
    synonymsUz: ['medical coat', 'tibbiyot xalat', 'doctor coat'],
    audience: 'erkaklar',
    segment: 'kiyim',
    pathUz: 'Erkaklar > Kiyim > Tibbiyot xalati',
    leaf: true,
  },
]

/**
 * Get all unique audiences
 */
export function getAudiences(): Audience[] {
  return ['erkaklar', 'ayollar', 'bolalar', 'unisex']
}

/**
 * Get audience label in Uzbek
 */
export function getAudienceLabel(audience: Audience): string {
  const labels: Record<Audience, string> = {
    erkaklar: 'Erkaklar',
    ayollar: 'Ayollar',
    bolalar: 'Bolalar',
    unisex: 'Barcha uchun',
  }
  return labels[audience]
}

/**
 * Get all unique segments
 */
export function getSegments(): Segment[] {
  return ['kiyim', 'oyoq_kiyim', 'aksessuar', 'ichki_kiyim', 'sport', 'milliy']
}

/**
 * Get segment label in Uzbek
 */
export function getSegmentLabel(segment: Segment): string {
  const labels: Record<Segment, string> = {
    kiyim: 'Kiyim',
    oyoq_kiyim: 'Oyoq kiyim',
    aksessuar: 'Aksessuar',
    ichki_kiyim: 'Ichki kiyim',
    sport: 'Sport',
    milliy: 'Milliy',
  }
  return labels[segment]
}
